"""Developed by: Matthew Findlay 2017

This module includes a class with several validation metrics and helper
functions for those validation metrics.
"""

import data_utils
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.exceptions import UndefinedMetricWarning
from sklearn.utils import column_or_1d
import math
import visualization_utils
import sklearn
from sklearn import metrics


class validation_metrics(object):
    """Several statistical tests used to validate the models predictive power

    Args:
        :param true_results (array of ints): The true testing values
        :param predicted_results (array of floats): The predicted probabilities
        generated by the model
    Attributes:
        :true_results (array of ints): The true testing values
        :predicted_results (array of floats): The predicted probabilities
        generated by the model
    """
    def __init__(self, true_results, predicted_results):
        self.true_results = true_results
        self.predicted_results = predicted_results
        self.mse = []
        self.rmse = []
        self.mae = []
        self.huber_loss = []

    def calculate_error_metrics(self):
        """Calculate various error metric values using several regression metrics like MSE, RMSE, Huber Loss,
        and store them into error-metric-specific lists

        Args, Returns: None
        """
        # as the model goes through the pipeline, keep all scores in their respective list, where the average of each
        # error metric is then obtained after all runs have been completed
        self.mse.append(metrics.mean_squared_error(y_true=self.true_results, y_pred=self.predicted_results))
        self.rmse.append(metrics.mean_squared_error(y_true=self.true_results, y_pred=self.predicted_results, squared=False))
        self.mae.append(metrics.mean_absolute_error(y_true=self.true_results, y_pred=self.predicted_results))
        self.huber_loss.append(self.calculate_huber_loss())

    def calculate_huber_loss(self):
        """Because sklearn doesn't provide an implementation of the Huber Loss error metric, this offers an
        implementation of the Huber Loss error metric

        Args, Returns: None
        """